# Generated by Django 5.2.14 on 2026-06-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
